name: Build

on:
    push: ~
    pull_request: ~
    release:
        types: [created]

jobs:
    tests:
        runs-on: ubuntu-latest

        name: "PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}"

        strategy:
            fail-fast: false
            matrix:
                php: [7.1, 7.2, 7.3, 7.4, 8.0, 8.1]
                symfony: [^3.4, ^4.4, ^5.2, ^6.0]
                exclude:
                    - { php: 7.1, symfony: ^5.2 }
                    - { php: 7.1, symfony: ^6.0 }
                    - { php: 7.2, symfony: ^6.0 }
                    - { php: 7.3, symfony: ^6.0 }
                    - { php: 7.4, symfony: ^6.0 }

        env:
            APP_ENV: test

        steps:
            -
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    extensions: intl
                    tools: symfony
                    coverage: none

            -
                name: Get Composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -
                name: Cache Composer
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json **/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-${{ matrix.php }}-composer-
            -
                name: Restrict Symfony version
                if: matrix.symfony != ''
                run: |
                    composer global require --no-progress --no-scripts --no-plugins "symfony/flex:^1.10"
                    composer config extra.symfony.require "${{ matrix.symfony }}"

            -
                name: Install PHP dependencies
                run: composer install --no-interaction

            -
                name: Run analysis
                run: composer validate --strict

            -
                name: Run PHPUnit
                run: vendor/bin/phpunit --colors=always
